Summarize lesson about function, pass, booleans and conditionals
MIMPython/mimpython.github.io pull request #35
Opened 2022-07-17 11:48 UTC by TranTuan2412

2022-07-17 13:46 UTC, quanhoang-pm requested changes

2022-07-17 13:46 UTC, quanhoang-pm commented on _pythonSummerCourse/02-02-method.md
> +  sum = a + b
Không nên dùng biến `sum`, vì nó làm một built-in function trong Python

2022-07-17 13:46 UTC, quanhoang-pm commented on _pythonSummerCourse/02-02-method.md
> +- Ở ví dụ trên, từ khóa `def` đánh dấu bắt đầu định nghĩa hàm, tên hàm `total`, đối số `a`, `b`. Hàm `total` trả về tổng của hai đối số nhập vào bằng phép gán ```sum = a + b```.
Vì sao dùng ba dấu ` thay vì một dấu ` ở phần cuối câu?

2022-07-17 13:46 UTC, quanhoang-pm commented on _pythonSummerCourse/02-02-method.md
> +print(sum(s, 24)) # 36
Tương tự lý do về hàm `sum` bên trên.

2022-07-17 13:46 UTC, quanhoang-pm commented on _pythonSummerCourse/02-02-method.md
> +def sum(*n):
`n`: tên biến không tốt.

2022-07-17 13:46 UTC, quanhoang-pm commented on _pythonSummerCourse/02-02-method.md
> +    s +=i
Thiếu dấu cách.

2022-07-17 13:46 UTC, quanhoang-pm commented on _pythonSummerCourse/02-02-method.md
> +    print('Chào',name,age,'tuổi')
- Thiếu dấu cách
- Phải dùng f-string thay vì kiểu print thông thường.

2022-07-17 13:46 UTC, quanhoang-pm commented on _pythonSummerCourse/02-02-method.md
> +greetUser(Anh = 10, Thảo = 20, Hoàng = 19, Trung = 33)
Tên biến không nên là tiếng Việt.

2022-07-17 13:55 UTC, quanhoang-pm commented on _pythonSummerCourse/02-02-method.md
> +greetUser(Anh = 10, Thảo = 20, Hoàng = 19, Trung = 33)
Hơn nữa viết viết `Thảo = 20` là rất khó hiểu.

2022-07-17 14:31 UTC, TranTuan2412 commented on _pythonSummerCourse/02-02-method.md
> +greetUser(Anh = 10, Thảo = 20, Hoàng = 19, Trung = 33)
Vâng ạ, em sẽ sửa và hoàn thiện trong hôm nay ạ

2022-07-17 18:39 UTC, quanhoang-pm requested changes
Tất cả những chỗ lùi đầu dòng cần đặt đúng 4 dấu cách (thay vì 2 dấu cách như hiện tại).

2022-07-17 19:29 UTC, TranTuan2412 commented
> Em chưa hiểu cho lắm ạ

2022-07-18 03:16 UTC, quanhoang-pm commented
@TranTuan2412 
Đây là nội dung hiện tại
```py
def greetUser():
  print("Hello!")
```

Còn đây là cách trình bày cần đạt được
```py
def greetUser():
    print("Hello!")
```

Tóm lại, tất cả những chỗ lùi đầu dòng **trong code** cần đặt đúng 4 dấu cách (thay vì 2 dấu cách như hiện tại).

2022-07-18 08:29 UTC, quanhoang-pm requested changes
@TranTuan2412 rà soát lại một lượt để đảm bảo chỉ sử dụng đúng 4 dấu cách cho mỗi lần lùi 1 level ở đầu dòng.
Đây là quy tắc tối thiểu cần đạt được khi viết code Python.

2022-07-18 08:29 UTC, quanhoang-pm commented on _pythonSummerCourse/02-02-method.md
> +      i += 1
Thừa khoảng cách.

2022-07-18 08:29 UTC, quanhoang-pm commented on _pythonSummerCourse/02-02-method.md
> +      pass
Thừa khoảng cách.

2022-07-18 08:29 UTC, quanhoang-pm commented on _pythonSummerCourse/02-02-method.md
> +
Bỏ dấu xuống dòng trong phần code này

2022-07-18 08:48 UTC, TranTuan2412 commented on _pythonSummerCourse/02-02-method.md
> +
Vâng ạ

2022-07-18 13:50 UTC, quanhoang-pm approved these changes

2022-07-18 13:50 UTC, quanhoang-pm commented on _pythonSummerCourse/02-02-method.md
> +
@TranTuan2412 chưa bỏ dấu xuống dòng ở đây à?

2022-07-18 13:51 UTC, merged