Summarize lessons about list comprehension
MIMPython/mimpython.github.io pull request #44
Opened 2022-07-22 10:19 UTC by TranTuan2412

2022-07-22 10:41 UTC, quanhoang-pm requested changes
@TranTuan2412 xem những nhận xét này và áp dụng nó cho tất cả những chỗ tương tự có trong bài và trong những bài tóm tắt sau nhé.

2022-07-22 10:41 UTC, quanhoang-pm commented on _pythonSummerCourse/04-03-list-comprehension.md
> +# 1. List comprehension
Dùng heading H2 `##` thôi. Vì title đã là H1 rồi.

2022-07-22 10:41 UTC, quanhoang-pm commented on _pythonSummerCourse/04-03-list-comprehension.md
> +result = ["Even" if i % 2 == 0 else "Odd" for i in range(5)]
Even -> even
Odd -> odd

2022-07-22 10:41 UTC, quanhoang-pm commented on _pythonSummerCourse/04-03-list-comprehension.md
> +  def add(number):
add -> double. Để tên hàm rõ nghĩa hơn.

2022-07-22 10:41 UTC, quanhoang-pm commented on _pythonSummerCourse/04-03-list-comprehension.md
> +  result = map(add, numbers)
Cần có thêm lệnh `print(result)` để thấy được rằng `result` không phải là một list.

2022-07-22 10:41 UTC, quanhoang-pm commented on _pythonSummerCourse/04-03-list-comprehension.md
> +          return False
-> `return number % 2 == 0`

2022-07-22 10:41 UTC, quanhoang-pm commented on _pythonSummerCourse/04-03-list-comprehension.md
> +  print(evenDict)
Viết thêm kết quả trong phần comment.

2022-07-22 10:41 UTC, quanhoang-pm commented on _pythonSummerCourse/04-03-list-comprehension.md
> +# Tài liệu tham khảo
Chia thành tài liệu chính và tài liệu bổ sung. Xem những bài tóm tắt trước.

2022-07-22 17:43 UTC, TranTuan2412 commented on _pythonSummerCourse/04-03-list-comprehension.md
> +# Tài liệu tham khảo
Vâng ạ, em sẽ chỉnh sửa và commit lại ạ

2022-07-25 07:06 UTC, quanhoang-pm approved these changes

2022-07-25 07:06 UTC, merged