Summarize lessons about exception, warning and debugger
MIMPython/mimpython.github.io pull request #65
Opened 2022-08-18 04:06 UTC by TranTuan2412

2022-08-18 09:19 UTC, quanhoang-pm requested changes
Một số đoạn code mới chỉ có 2 dấu cách thay vì 4.

2022-08-18 09:19 UTC, quanhoang-pm commented on _pythonSummerCourse/07-02-custom-error-warning.md
> +- Python sử dụng một đối tượng đặc biệt gọi là `exceptions` để quản lý lỗi xảy ra trong quá trình thực hiện chương trình.
exceptions -> exception

2022-08-18 09:19 UTC, quanhoang-pm commented on _pythonSummerCourse/07-02-custom-error-warning.md
> +### 1.1. `Raise`
`Raise` -> Từ khóa `raise`.

Không có từ khóa `Raise`, chỉ có từ khóa `raise`.

2022-08-18 09:19 UTC, quanhoang-pm commented on _pythonSummerCourse/07-02-custom-error-warning.md
> +    raise Exception("Numbers below zero")
thiếu spaces.

2022-08-18 09:19 UTC, quanhoang-pm commented on _pythonSummerCourse/07-02-custom-error-warning.md
> +- Khối `try` and `except` được sử dụng để catch và handle ngoại lệ.
"catch và handle" -> Việt hóa chúng và nếu cần thì đặt nghĩa tiếng Anh trong ngoặc.

2022-08-18 09:19 UTC, quanhoang-pm commented on _pythonSummerCourse/07-02-custom-error-warning.md
> +
Bổ sung thêm một ví dụ thể hiện toàn bộ kiến thức về try/except/else/finally. Ý tưởng là thiết kế nó ở trong một hàm, để đưa vào nhiều kiểu tham số để nó đi vào các trường hợp khác nhau.

Yêu cầu: phải có ít nhất hai lần dùng `except`.

2022-08-18 09:19 UTC, quanhoang-pm commented on _pythonSummerCourse/07-02-custom-error-warning.md
> +
Cho ví dụ.

2022-08-18 09:19 UTC, quanhoang-pm commented on _pythonSummerCourse/07-02-custom-error-warning.md
> +  ....> python -m pdb divisionCaculator.py
Không nhất thiết phải dùng `-m pdb`. Nói như vậy **không có nghĩa** là chỉ thực hiện việc xóa đi `-m pdb` trong câu lệnh trên.

2022-08-18 09:38 UTC, TranTuan2412 commented on _pythonSummerCourse/07-02-custom-error-warning.md
> +  ....> python -m pdb divisionCaculator.py
Vâng ạ. Em đã đọc các nhận xét của anh và sẽ chỉnh sửa ạ.

2022-08-19 03:51 UTC, TranTuan2412 commented
Anh @quanhoang-pm  ơi, anh xem lại giúp em nhé. Ở chỗ bỏ -m pdb thì em chưa tìm hiểu được ạ.

2022-08-19 04:02 UTC, quanhoang-pm requested changes

2022-08-19 04:02 UTC, quanhoang-pm commented on _pythonSummerCourse/07-02-custom-error-warning.md
> +
Hai lần dùng except phải ngang cấp với nhau, mỗi lần bắt một lỗi khác nhau, KHÔNG phải lồng nhau như hiện tại.

Ví dụ: thực hiện việc lấy giá trị lớn nhất của một list chia cho độ dài của list đó. Sẽ có hai lỗi có thể xảy ra.

2022-08-19 04:02 UTC, quanhoang-pm commented on _pythonSummerCourse/07-02-custom-error-warning.md
> +  ....> python -m pdb divisionCaculator.py
Vẫn giữ chương trình như trên, chạy lệnh `python divisionCaculator.py` xem chuyện gì xảy ra.

2022-08-19 04:02 UTC, quanhoang-pm commented on _pythonSummerCourse/07-02-custom-error-warning.md
> +  import pdb; pdb.set_trace()
Không dùng dấu `;`

2022-08-19 04:02 UTC, quanhoang-pm commented on _pythonSummerCourse/07-02-custom-error-warning.md
> +
Ví dụ trong [link](https://realpython.com/python-exceptions/#:~:text=Look%20at%20the%20following%20code.%20Here%2C%20you%20first%20call%20the%20linux_interaction()%20function%20and%20then%20try%20to%20open%20a%20file%3A) sau.

2022-08-21 19:48 UTC, merged

2022-08-28 16:07 UTC, quanhoang-pm commented
@TranTuan2412